### ISSUE TITLE
Google firebase function/index.js

### ISSUE THREAD

**Issue by Robert126** [google/voice-builder#34]
When I am building an App with Flutter connecting to Firebase. When deploying the function/index.js
I am getting the following Error:

Hopefully some one can help me out?

Kind regards,
Robert

    firebase deploy --only functions
    === Deploying to 'flutter-products-270517'...

     i  deploying functions
     i  functions: ensuring necessary APIs are enabled...
    ✔  functions: all necessary APIs are enabled
    i  functions: preparing functions directory for uploading...

    Error: Error occurred while parsing your function triggers.

    TypeError: require(...) is not a function
        at Object.<anonymous> (/Users/Robert/development/flutter_course/functions/index.js:21:45)
        at Module._compile (internal/modules/cjs/loader.js:1147:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
        at Module.load (internal/modules/cjs/loader.js:996:32)
        at Function.Module._load (internal/modules/cjs/loader.js:896:14)
        at Module.require (internal/modules/cjs/loader.js:1036:19)
        at require (internal/modules/cjs/helpers.js:72:18)
        at /usr/local/lib/node_modules/firebase-tools/lib/triggerParser.js:15:15
        at Object.<anonymous> (/usr/local/lib/node_modules/firebase-tools/lib/triggerParser.js:53:3)
        at Module._compile (internal/modules/cjs/loader.js:1147:30)

-----------------------
    const functions = require('firebase-functions');
    const cors = require('cors')({ origin: true });
    const Busboy = require('busboy');
    const os = require('os');
    const path = require('path');
    const fs = require('fs');
    const fbAdmin = require('firebase-admin');
    const uuid = require('uuid/v4');

    // // Create and Deploy Your First Cloud Functions
    // // https://firebase.google.com/docs/functions/write-firebase-functions
    //
    // exports.helloWorld = functions.https.onRequest((request, response) => {
    //  response.send("Hello from Firebase!");
    // });
    const gcconfig = {
        projectId: 'flutter-productsXXXXXX',
        keyFilename: 'XXXXX.json'
    };

    const gcs = require('@google-cloud/storage')(gcconfig);
    // const {gcs} = require('@google-cloud/storage')(gcconfig);

    fbAdmin.initializeApp({
        credential: fbAdmin.credential.cert(require('./flutter-products.json'))
    });

    exports.storeImage = functions.https.onRequest((req, res) => {
        return cors(req, res, () => {
            if (req.method !== 'POST') {
                return res.status(500).json({ message: 'Not allowed.' });
            }

            if (
                 !req.headers.authorization ||
            !req.headers.authorization('Bearer ')
            ) {
                 return res.status(401).json({ error: 'Unauthorized.' });
            }

            let idToken;
            idToken = req.headers.authorization.split('Bearer ')[1];

            const busboy = new Busboy({ headers: req.headers });
            let uploadData;
            let oldImagePath;

            busboy.on('file', (fieldname, file, filename, encoding, mimetype) => {
                const filePath = path.join(os.tmpdir(), filename);
                uploadData = { filePath: filePath, type: mimetype, name: filename };
                file.pipe(fs.createWriteStream(filePath));
            });

            busboy.on('field', (fieldname, value) => {
                oldImagePath = decodeURIComponent(value);
            });

            busboy.on('finish', () => {
                const bucket = gcs.bucket('flutter-productsXXXXXX.appspot.com');
                const id = uuid();
                let imagePath = 'images/' + id + '-' + uploadData.name
                if (oldImagePath) {
                    imagePath = oldImagePath;
                }

                return fbAdmin
                    .auth()
                    .verifyIdToken(idToken)
                    .then(decodedToken => {
                         return bucket.upload(uploadData.filePath, {
                            uploadType: 'media',
                            destination: imagePath,
                            metadata: {
                                metadata: {
                                    contentType: uploadData.type,
                                    firebaseStorageDownloadToken: id
                                }
                            }
                        });
                    })
                    .then(() => {
                        return res.status(201).json({
                            imageUrl: 'https://firebasestorage.googleapis.com/v0/b/' +
                                bucket.name +
                                '/o/' +
                                encodeURIComponent(imagePath) +
                                '?alt=media&token=' +
                                id,
                                imagePath: imagePath
                        });
                    })
                    .catch(error => {
                        return res.status(401).json({ error: 'Unauthorized!' });
                    });
            });
            return busboy.end(req.rawBody);
        });
});

**Comment by pasindud** [comment]
Seems this question is not related to voice builder
