### ISSUE TITLE
Creating GCS buckets fails 

### ISSUE THREAD

**Issue by WieMaKa** [google/voice-builder#51]
Hi,
When I am trying to run `./deploy.sh initial_setup` I am receiving a few errors.
from file deploy.sh:
![Screenshot at Sep 24 00-03-38](https://user-images.githubusercontent.com/66131143/94074403-76339f00-fdf9-11ea-86de-b63e48153e64.png)
This are the changes I made in file deploy.sh : 
<img width="716" alt="Screenshot at Sep 24 00-05-08" src="https://user-images.githubusercontent.com/66131143/94074570-da566300-fdf9-11ea-844e-14d0075ab9ac.png">

Any ideas why this occurs?

**Comment by pasindud** [comment]
Remove "<" and ">" from the placeholders

**Comment by WieMaKa** [comment]
thank you for your fast answer. I made next to your suggestion changes in line 17, because the same massage with errors was occurring from pic above: line 17: bad substitution  
<img width="702" alt="Screenshot at Sep 24 17-37-08" src="https://user-images.githubusercontent.com/66131143/94167627-fd7e2280-fe8c-11ea-9cad-b72362730725.png">

This led me to another issue
To have access to gcloud I also needed to install gsutil and configure with following line of code:
`gsutil config -w`

I found this solution here: 
[https://cloud.google.com/storage/docs/gsutil/commands/config](url)

best regards
