### ISSUE TITLE
Status Code: -1

### ISSUE THREAD

**Issue by mirfan899** [google/voice-builder#8]
I've successfully deployed the `voice-builder` on GCP but when I try to train `sinhala` example is shows following error.
<img width="669" alt="Screen Shot 2019-06-16 at 2 22 29 PM" src="https://user-images.githubusercontent.com/3822565/59563234-8387a880-9050-11e9-97b6-e3bc45363161.png">

**Comment by mirfan899** [comment]
ui VM shows following error
```shell
Bucket is requester pays bucket but no user project provided.
```

**Comment by mirfan899** [comment]
After reinstalling all, the logs now show
```text
Error calling D-Bus proxy call to interface '/org/chromium/SessionManager': The name org.chromium.SessionManager was not provided by any .service files
```

**Comment by pasindud** [comment]
What is the lexicon path you gave ?

**Comment by mirfan899** [comment]
<img width="1439" alt="Screen Shot 2019-06-24 at 2 15 57 PM" src="https://user-images.githubusercontent.com/3822565/60006858-a2a6bb80-968a-11e9-8c48-2d6e0d17ff48.png">

**Comment by mirfan899** [comment]
This specific issue is resolved by modifying the bucker permissions.

**Comment by prathamApp** [comment]
Hey @mirfan899 can you please explain what are the modifications you did in bucket permissions?

Every help would be appreciated.
